// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARrEr2zNx7dWXJFkhEqKIIrDt9Cewc1iU',
    appId: '1:1036905477462:web:f43219284ffc0e5eeb52f7',
    messagingSenderId: '1036905477462',
    projectId: 'earthquake-62cca',
    authDomain: 'earthquake-62cca.firebaseapp.com',
    storageBucket: 'earthquake-62cca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHGZ9B9t5xIDBvUwduheqjNrLiROT4ZxM',
    appId: '1:1036905477462:android:40a32a3f3025b203eb52f7',
    messagingSenderId: '1036905477462',
    projectId: 'earthquake-62cca',
    storageBucket: 'earthquake-62cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH15rPQ6Bmx6AuE0soZnzrgs6whXokoJc',
    appId: '1:1036905477462:ios:3bb1585c8f2736faeb52f7',
    messagingSenderId: '1036905477462',
    projectId: 'earthquake-62cca',
    storageBucket: 'earthquake-62cca.appspot.com',
    iosClientId: '1036905477462-1f9gc864jmcfbl39iu2g22cvv4oagqok.apps.googleusercontent.com',
    iosBundleId: 'com.example.earthquakes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH15rPQ6Bmx6AuE0soZnzrgs6whXokoJc',
    appId: '1:1036905477462:ios:3bb1585c8f2736faeb52f7',
    messagingSenderId: '1036905477462',
    projectId: 'earthquake-62cca',
    storageBucket: 'earthquake-62cca.appspot.com',
    iosClientId: '1036905477462-1f9gc864jmcfbl39iu2g22cvv4oagqok.apps.googleusercontent.com',
    iosBundleId: 'com.example.earthquakes',
  );
}
